apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE
  namespace: cascade-example
  labels:
    app: SERVICE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SERVICE
  template:
    metadata:
      labels:
        app: SERVICE
    spec:
      containers:
      - command:
        args:
        - --service-name=SERVICE
        - --pod-name=$(POD_ID)
        - --op-weight-millicore-duration=WEIGHT
        - --generate-ops=GEN
        - --ops-limit=LIMIT
        - --dependencies=DEPS
        image: github.com/josephburnett/cascade-example/cmd
        imagePullPolicy: Always
        name: cascade-example
        resources:
          requests:
            cpu: CPU
          limits:
            cpu: CPU
        env:
        - name: POD_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.5.0
        command:
        - /monitor
        - --source=:http://localhost:8080
        - --stackdriver-prefix=custom.googleapis.com
        - --pod-id=$(POD_ID)
        - --namespace-id=$(POD_NAMESPACE)
        resources:
          requests:
            cpu: 1m
        env:
        - name: POD_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: SERVICE
  namespace: cascade-example
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: SERVICE
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: SERVICE
  namespace: cascade-example
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Object
    object:
      target:
        kind: Pod
        name: metrics
      metricName: custom.googleapis.com|ingress_qps
      targetValue: "50"
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: SERVICE
